name: build-kernel

on:
  workflow_dispatch:

  schedule:
    - cron: "0 1 * * 0"

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Build dockerfile
        run: docker build -t personal-kernel .

      - name: Query source code version
        run: docker run --rm -v${PWD}/build:/build personal-kernel /query.sh

      - name: Check release exist
        run: |
          gh release view $(cat build/version) || touch updated

      - name: Build kernel
        run: |
          if [ -f updated ]; then
            docker run --rm -v${PWD}/build:/build personal-kernel /build.sh
          fi

      - name: Upload kernel
        run: |
          if [ -f updated ]; then
            gh release create -t $(cat build/version) -F build/version $(cat build/version) build/*.deb build/*.buildinfo build/*.changes build/version 
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
